services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_img_test.asgi:application -k uvicorn.workers.UvicornWorker"
